version: "3.8"
services:
  #PHP Service
  vanilla_php_fpm:
    build:
      context: ./backend
      args:
        APPLICATION_ENVIRONMENT: ${APP_ENV}
    image: vanilla_php_fpm
    container_name: vanilla_php_fpm
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
    working_dir: /var/www/html
    networks:
      - backend-network
    volumes:
       - ./backend:/var/www/html:cached
       - ./backend/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  #Nginx Service
  vanilla_nginx:
    image: nginx:alpine
    container_name: vanilla_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    depends_on:
      - vanilla_php_fpm
    networks:
      - backend-network
    volumes:
      - ./backend:/var/www/html:cached
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx

  #MySQL Service
  vanilla_mysql:
    image: mysql:5.7
    container_name: vanilla_mysql
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - backend-network

#Docker Networks
networks:
  backend-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
